#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $LN -sf "$1" "$2"
}
handle_file_ln "/home/rongzi/.dotfiles/bashrc" "/home/rongzi/.bashrc"
handle_file_ln "/home/rongzi/.dotfiles/config/alacritty/alacritty.yml" "/home/rongzi/.config/alacritty/alacritty.yml"
handle_file_ln "/home/rongzi/.dotfiles/config/dwm/config.h" "/home/rongzi/.config/dwm/config.h"
handle_file_ln "/home/rongzi/.dotfiles/config/dwm/dwm.c" "/home/rongzi/.config/dwm/dwm.c"
handle_file_ln "/home/rongzi/.dotfiles/config/dwm/patch/dwm-actualfullscreen-20211013-cb3f58a.diff" "/home/rongzi/.config/dwm/patch/dwm-actualfullscreen-20211013-cb3f58a.diff"
handle_file_ln "/home/rongzi/.dotfiles/config/dwm/patch/dwm-alttab-6.4.diff" "/home/rongzi/.config/dwm/patch/dwm-alttab-6.4.diff"
handle_file_ln "/home/rongzi/.dotfiles/config/dwm/patch/dwm-alwayscenter-20200625-f04cac6.diff" "/home/rongzi/.config/dwm/patch/dwm-alwayscenter-20200625-f04cac6.diff"
handle_file_ln "/home/rongzi/.dotfiles/config/dwm/patch/dwm-anybar-polybar-tray-fix-20200810-bb2e722.diff" "/home/rongzi/.config/dwm/patch/dwm-anybar-polybar-tray-fix-20200810-bb2e722.diff"
handle_file_ln "/home/rongzi/.dotfiles/config/dwm/patch/dwm-autostart-20210120-cb3f58a.diff" "/home/rongzi/.config/dwm/patch/dwm-autostart-20210120-cb3f58a.diff"
handle_file_ln "/home/rongzi/.dotfiles/config/dwm/patch/dwm-fullgaps-6.4.diff" "/home/rongzi/.config/dwm/patch/dwm-fullgaps-6.4.diff"
handle_file_ln "/home/rongzi/.dotfiles/config/dwm/patch/dwm-ipc-20201106-f04cac6.diff" "/home/rongzi/.config/dwm/patch/dwm-ipc-20201106-f04cac6.diff"
handle_file_ln "/home/rongzi/.dotfiles/config/i3/config" "/home/rongzi/.config/i3/config"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/launch.sh" "/home/rongzi/.config/polybar/launch.sh"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/apps.ini" "/home/rongzi/.config/polybar/pwidgets/apps.ini"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/colors.ini" "/home/rongzi/.config/polybar/pwidgets/colors.ini"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/cpu.ini" "/home/rongzi/.config/polybar/pwidgets/cpu.ini"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/fs.ini" "/home/rongzi/.config/polybar/pwidgets/fs.ini"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/launch.sh" "/home/rongzi/.config/polybar/pwidgets/launch.sh"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/main_for_i3.ini" "/home/rongzi/.config/polybar/pwidgets/main_for_i3.ini"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/main.ini" "/home/rongzi/.config/polybar/pwidgets/main.ini"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/memory.ini" "/home/rongzi/.config/polybar/pwidgets/memory.ini"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/mpd.ini" "/home/rongzi/.config/polybar/pwidgets/mpd.ini"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/scripts/launcher.sh" "/home/rongzi/.config/polybar/pwidgets/scripts/launcher.sh"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/scripts/my_powermenu.sh" "/home/rongzi/.config/polybar/pwidgets/scripts/my_powermenu.sh"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/scripts/powermenu.sh" "/home/rongzi/.config/polybar/pwidgets/scripts/powermenu.sh"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/scripts/pywal.sh" "/home/rongzi/.config/polybar/pwidgets/scripts/pywal.sh"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/scripts/random.sh" "/home/rongzi/.config/polybar/pwidgets/scripts/random.sh"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/scripts/rofi/colors.rasi" "/home/rongzi/.config/polybar/pwidgets/scripts/rofi/colors.rasi"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/scripts/rofi/confirm.rasi" "/home/rongzi/.config/polybar/pwidgets/scripts/rofi/confirm.rasi"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/scripts/rofi/launcher.rasi" "/home/rongzi/.config/polybar/pwidgets/scripts/rofi/launcher.rasi"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/scripts/rofi/message.rasi" "/home/rongzi/.config/polybar/pwidgets/scripts/rofi/message.rasi"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/scripts/rofi/networkmenu.rasi" "/home/rongzi/.config/polybar/pwidgets/scripts/rofi/networkmenu.rasi"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/scripts/rofi/powermenu.rasi" "/home/rongzi/.config/polybar/pwidgets/scripts/rofi/powermenu.rasi"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/scripts/rofi/styles.rasi" "/home/rongzi/.config/polybar/pwidgets/scripts/rofi/styles.rasi"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/scripts/styles.sh" "/home/rongzi/.config/polybar/pwidgets/scripts/styles.sh"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/scripts/style-switch.sh" "/home/rongzi/.config/polybar/pwidgets/scripts/style-switch.sh"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/system.ini" "/home/rongzi/.config/polybar/pwidgets/system.ini"
handle_file_ln "/home/rongzi/.dotfiles/config/polybar/pwidgets/workspace.ini" "/home/rongzi/.config/polybar/pwidgets/workspace.ini"
handle_file_ln "/home/rongzi/.dotfiles/config/pylintrc" "/home/rongzi/.config/pylintrc"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/恢复键盘" "/home/rongzi/.config/scripts/恢复键盘"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/禁用键盘" "/home/rongzi/.config/scripts/禁用键盘"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/alacritty" "/home/rongzi/.config/scripts/alacritty"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/align" "/home/rongzi/.config/scripts/align"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/android" "/home/rongzi/.config/scripts/android"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/background" "/home/rongzi/.config/scripts/background"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/backlight" "/home/rongzi/.config/scripts/backlight"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/bash_for_joshuto" "/home/rongzi/.config/scripts/bash_for_joshuto"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/bluetooth.sh" "/home/rongzi/.config/scripts/bluetooth.sh"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/btop" "/home/rongzi/.config/scripts/btop"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/clipboard" "/home/rongzi/.config/scripts/clipboard"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/copyq" "/home/rongzi/.config/scripts/copyq"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/fonts" "/home/rongzi/.config/scripts/fonts"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/functions.sh" "/home/rongzi/.config/scripts/functions.sh"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/fzf_for_history.sh" "/home/rongzi/.config/scripts/fzf_for_history.sh"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/fzf_for_vim.sh" "/home/rongzi/.config/scripts/fzf_for_vim.sh"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/joshuto" "/home/rongzi/.config/scripts/joshuto"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/kdeconnect" "/home/rongzi/.config/scripts/kdeconnect"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/lock" "/home/rongzi/.config/scripts/lock"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/marco.sh" "/home/rongzi/.config/scripts/marco.sh"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/matrix" "/home/rongzi/.config/scripts/matrix"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/mouse_shot" "/home/rongzi/.config/scripts/mouse_shot"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/my_picom" "/home/rongzi/.config/scripts/my_picom"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/picom" "/home/rongzi/.config/scripts/picom"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/preview" "/home/rongzi/.config/scripts/preview"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/printer.py" "/home/rongzi/.config/scripts/printer.py"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/record_battery" "/home/rongzi/.config/scripts/record_battery"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/sensors.sh" "/home/rongzi/.config/scripts/sensors.sh"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/shot" "/home/rongzi/.config/scripts/shot"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/startup" "/home/rongzi/.config/scripts/startup"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/suspend" "/home/rongzi/.config/scripts/suspend"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/toggle_bluetooth.sh" "/home/rongzi/.config/scripts/toggle_bluetooth.sh"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/truecolor" "/home/rongzi/.config/scripts/truecolor"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/volume" "/home/rongzi/.config/scripts/volume"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/volume.sh" "/home/rongzi/.config/scripts/volume.sh"
handle_file_ln "/home/rongzi/.dotfiles/config/scripts/wrapper.sh" "/home/rongzi/.config/scripts/wrapper.sh"
handle_file_ln "/home/rongzi/.dotfiles/config/shell/completion.bash" "/home/rongzi/.config/shell/completion.bash"
handle_file_ln "/home/rongzi/.dotfiles/config/shell/completion.zsh" "/home/rongzi/.config/shell/completion.zsh"
handle_file_ln "/home/rongzi/.dotfiles/config/shell/key-bindings.bash" "/home/rongzi/.config/shell/key-bindings.bash"
handle_file_ln "/home/rongzi/.dotfiles/config/shell/key-bindings.fish" "/home/rongzi/.config/shell/key-bindings.fish"
handle_file_ln "/home/rongzi/.dotfiles/config/shell/key-bindings.zsh" "/home/rongzi/.config/shell/key-bindings.zsh"
handle_file_ln "/home/rongzi/.dotfiles/config/tmux/tmux.conf" "/home/rongzi/.config/tmux/tmux.conf"
handle_file_ln "/home/rongzi/.dotfiles/gitconfig" "/home/rongzi/.gitconfig"
handle_file_ln "/home/rongzi/.dotfiles/install.sh" "/home/rongzi/.install.sh"
handle_file_ln "/home/rongzi/.dotfiles/profile" "/home/rongzi/.profile"
handle_file_ln "/home/rongzi/.dotfiles/vim/autoload/airline/themes/onedark.vim" "/home/rongzi/.vim/autoload/airline/themes/onedark.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/autoload/lightline/colorscheme/onedark.vim" "/home/rongzi/.vim/autoload/lightline/colorscheme/onedark.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/autoload/onedark.vim" "/home/rongzi/.vim/autoload/onedark.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/autoload/plug.vim" "/home/rongzi/.vim/autoload/plug.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/autoload/tokyonight/airline/themes/tokyonight.vim" "/home/rongzi/.vim/autoload/tokyonight/airline/themes/tokyonight.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/autoload/tokyonight/lightline/colorscheme/tokyonight.vim" "/home/rongzi/.vim/autoload/tokyonight/lightline/colorscheme/tokyonight.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/colors/onedark.vim" "/home/rongzi/.vim/colors/onedark.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/colors/tokyonight.vim" "/home/rongzi/.vim/colors/tokyonight.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/functions/grep-operator.vim" "/home/rongzi/.vim/functions/grep-operator.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/functions/higherorder.vim" "/home/rongzi/.vim/functions/higherorder.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/functions/mode.vim" "/home/rongzi/.vim/functions/mode.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/functions/test_operator.vim" "/home/rongzi/.vim/functions/test_operator.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/functions/useful.vim" "/home/rongzi/.vim/functions/useful.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/spell/en.utf-8.add" "/home/rongzi/.vim/spell/en.utf-8.add"
handle_file_ln "/home/rongzi/.dotfiles/vim/spell/en.utf-8.add.spl" "/home/rongzi/.vim/spell/en.utf-8.add.spl"
handle_file_ln "/home/rongzi/.dotfiles/vim/syntax/ansi.vim" "/home/rongzi/.vim/syntax/ansi.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/syntax/bash.vim" "/home/rongzi/.vim/syntax/bash.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/syntax/cc.vim" "/home/rongzi/.vim/syntax/cc.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/syntax/c.vim" "/home/rongzi/.vim/syntax/c.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/syntax/java.vim" "/home/rongzi/.vim/syntax/java.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/syntax/python.vim" "/home/rongzi/.vim/syntax/python.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/syntax/qf.vim" "/home/rongzi/.vim/syntax/qf.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/syntax/rust.vim" "/home/rongzi/.vim/syntax/rust.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/syntax/sh.vim" "/home/rongzi/.vim/syntax/sh.vim"
handle_file_ln "/home/rongzi/.dotfiles/vim/syntax/vim.vim" "/home/rongzi/.vim/syntax/vim.vim"
handle_file_ln "/home/rongzi/.dotfiles/vimrc" "/home/rongzi/.vimrc"
handle_file_ln "/home/rongzi/.dotfiles/zshrc" "/home/rongzi/.zshrc"
