#!/bin/bash

if  pgrep i3lock ;then
    exec logger --tag 'i3lock' 'screen is locked, i3lock is not starting'
fi
BLANK='#00000000'
CLEAR='#ffffff22'
# DEFAULT='#00897bE6'
DEFAULT='#00fffbE6'
# TEXT='#00897bE6'
TEXT='#CCCCCC'
WRONG='#880000bb'
VERIFYING='#00564dE6'

i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 5                     \
--clock                      \
--indicator                  \
--time-str="%H:%M:%S"        \
--date-str=" %Y-%m-%d"       \
--keylayout 1
