#!/usr/bin/bash

shot_name=$(get_shot_path)
shot_path=$shot_dir/$shot_name

$notify -r $notification_id -t 2000 -i $shot_icon "截图" "选择窗口或框出一个矩形"
maim -m 6 -f png -s $shot_path

if [[ -f "$shot_path" ]];then
    $notify -r $notification_id -t 1800 -i $shot_icon  "保存为" "$shot_name"
    echo "$shot_path" | gpaste-client add

    for id in $(kdeconnect-cli -a | grep -Po '(?<=^-.{,100}: ).[^[:blank:]]*');do
        kdeconnect-cli -d "$id" --share "$shot_path" &
        $notify -t 1800 -i $shot_icon  "发送到" "$id"
    done

else
    $notify -r $notification_id -i $error_icon "选择无效！"
fi
