#!/bin/bash
preview() {
    if [[ -f $1 ]]; then
        # head -n 50 $2
        bat --color always $1 | head -n 50
    else
        # exa --color='always' -l $1
        tree -C $1 | head -n 50
    fi
}
preview $1
