#!/bin/bash
info=$(acpi)
state=$(awk '{print $NF}' <(echo $info))
time=$(date -u '+%Y-%m-%d %H:%M:%S')

if [[ $state = "100%" ]];then
    echo ---------FULL------------ >> $HOME/.log/battery.log
elif [[ $state = "charged" ]];then
    echo $time: $info >> $HOME/.log/battery.log
elif [[ $state = "remaining" ]];then
    echo $time: $info >> $HOME/.log/battery.log
    remaining=$(acpi | awk '{print $(NF-1), $NF}')
fi
