#!/bin/bash
time=$(date "+%y-%m-%d_%H:%M:%S")

maim -m 10 $shot_path

if [[ -f "$shot_path" ]];then
    dunstify -r $notification_id -t 1800 -I $shot_icon "截图保存为" "$time.png"
else
    dunstify -r $notification_id -I $error_icon "截图无效！"
fi
