#!/bin/bash

shot_name=$(get_shot_path)
shot_path=$shot_dir/$shot_name

maim -m 5 -f png $shot_path

if [[ -f "$shot_path" ]];then
    # timeout 5 $notify -r $notification_id -t 15000 -i $shot_icon -A "ocr:$shot_path=识别" "截图保存为" "$shot_name"
    echo "$shot_path" | gpaste-client add
    timeout 5 $notify -r $notification_id -t 5000 -A "ocr:$shot_path=识别" "截图保存为" "$shot_name"
    for id in $(kdeconnect-cli -a | grep -Po '(?<=^-.{,100}: ).[^[:blank:]]*');do
        kdeconnect-cli -d "$id" --share "$shot_path"
        if [[ $? -eq 0 ]];then
            $notify -t 1800 -i $shot_icon  "发送到" "$id"
        else
            $notify -t 1800 -i $shot_icon  "没能发送到" "$id"
        fi
    done
else
    $notify -r $notification_id -i $error_icon "截图无效！"
fi
