#!/bin/bash

shot_name=$(get_shot_path)
shot_path=$shot_dir/$shot_name

maim -m 5 -f png $shot_path

if [[ -f "$shot_path" ]];then
    dunstify -r $notification_id -t 1800 -I $shot_icon "截图保存为" "$shot_name"
    echo "$shot_path" | gpaste-client add
else
    dunstify -r $notification_id -I $error_icon "截图无效！"
fi
