#!/bin/bash

picom -b &
fcitx5 &
# ~/.config/scripts/background &
dunstify -t 3000 -I $manjaro_icon "rongzi, welcome back!"
clash -f ~/.config/clash/profiles/$(/bin/ls ~/.config/clash/profiles | grep -E "[0-9]+.yml" | sort | tail -n1) &
