notification:
  app-icon:

    ### If set to true: If no icon is passed by the app_icon parameter
    ### and no application "desktop-entry"-hint is present, deadd will
    ### try to guess the icon from the application name (if present).
    guess-icon-from-name: true

    ### The display size of the application icons in the notification
    ### pop-ups and in the notification center
    icon-size: 20
  dbus:
    send-noti-closed: true
  popup:
    default-timeout: 3000
    margin-top: 50
    margin-right: 50
    width: 420
  modifications:
    - match:
        title: "保存为"
      script: "/home/rongzi/.config/ocr_client/ocr_modify.py"
    - match:
        title: "截图保存为"
      script: "/home/rongzi/.config/ocr_client/ocr_modify.py"
    - match:
        title: "OCR 失败"
      script: "/home/rongzi/.config/ocr_client/ocr_modify.py"
    - match:
        title: "OCR 结果"
        script: "/home/rongzi/.config/ocr_client/ocr_modify.py"
      modify:
        action-commands:
          copy: "nohup /home/rongzi/.config/ocr_client/ocr_copy.sh >/dev/null 2>&1 &"
